language: node_js
node_js:
- '0.10'
addons:
  code_climate:
    repo_token: 9e19dee6114553cd4ae00b735b065a24488f5aa8192017570afc5594474f312e
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key:
    secure: NlWOqEuCBRM7XoFbBpvpgF/3OTVWvDEhpPpxagaC8LudVwQK1/6ajEjOUcz6FfPqQ0eNbWCv7bNMLs9gnnn2mSrRe635ZMG5rJdSyk4qDqjVLCr6sTJRWrStyfjv+HXhIpiRuGcN+Bpi25BxDkCGI8I2yPDMAYXYXKY4MU9Do9A=
  on:
    tags: true
    repo: simbo/metalsmith-better-excerpts
    all_branches: true
before_script:
- npm install -g mocha istanbul codeclimate-test-reporter
after_script:
- npm run cover
- cat coverage/lcov.info | codeclimate
