language: node_js
node_js:
- '0.10'
addons:
  code_climate:
    repo_token: 9e19dee6114553cd4ae00b735b065a24488f5aa8192017570afc5594474f312e
deploy:
  provider: npm
  email: simbo@simbo.de
  api_key:
    secure: YZiPc7Q0QkAZgqPgQ9S5Ezd4KIASVWHB0RqxRGG+s5amhkHP0gZ+5U7Qmxe5SqEafjT6pA8/JALf/ehDGEkyVI0Sgn6IloXBkrDwtqCwUsZiqre8FlNWacHu3biNP3Xseo78PoSZ0nzLfEMPracO/0frdNYmCF4Kf+OMc7R+YfU=
  on:
    tags: true
    repo: simbo/metalsmith-better-excerpts
    all_branches: true
after_script:
- npm run cover
- cat coverage/lcov.info | ./node_modules/.bin/codeclimate
